<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TQID2SQ" failures="1" tests="4" name="LambdaTest01.Test1" time="1.343" errors="0" timestamp="2023-08-28T11:36:49 IST" skipped="0">
  <testcase classname="LambdaTest01.Test1" name="tearDown" time="0.197">
    <failure message="The following asserts failed:
	 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
	 **** Check Box already selected  **** expected [false] but found [true],
	**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
 ****Title Not matched**** expected [Selenium Grid Online | Run Selenium Test On Cloud--] but found [Selenium Grid Online | Run Selenium Test On Cloud],
 **** Check Box already selected  **** expected [false] but found [true],
**** Alert Box message Not Matched! ****** expected [I am an alert box!--] but found [I am an alert box!]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at LambdaTest01.Test1.tearDown(Test1.java:140)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tearDown -->
  <testcase classname="LambdaTest01.Test1" name="Test_Scenario_01" time="0.029"/>
  <testcase classname="LambdaTest01.Test1" name="Test_Scenario_02" time="0.644"/>
  <testcase classname="LambdaTest01.Test1" name="Test_Scenario_03" time="0.473"/>
</testsuite> <!-- LambdaTest01.Test1 -->
